// <auto-generated />
namespace TwentyTwoVzn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class csdfcds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csdfcds));
        
        string IMigrationMetadata.Id
        {
            get { return "202104301427095_csdfcds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
